### ISSUE TITLE
Don't even upgrade pip and setuptools are root

### ISSUE THREAD

**Issue by tiran** [peterpakos/checkipaconsistency#46]
See #45, README still contains this:
```
sudo pip install --upgrade pip setuptools
```

**Comment by peterpakos** [comment]
That was put there on purpose.

Upgrading those 2 shouldn't cause any problems, right?

**Comment by tiran** [comment]
pip maybe, but setuptools update will cause issues.

CentOS and RHEL ship an old version of setuptools with big internal API differences to modern setuptools. If your application requires a more recent version of setuptools and pip to install, then you have to use a virtual env and update both inside the virtual env.
