### ISSUE TITLE
Sudo rules not synced?

### ISSUE THREAD

**Issue by j-pavel** [peterpakos/checkipaconsistency#48]
### Expected behaviour
Accurately detect failures deeper than "count" for sudo rules

### Actual behaviour
Check passes, even with an underlying problem

### Steps to reproduce the behaviour
Running FreeIPA 4.4. Somehow, a node gets out of sync - changes to a sudo rule were not getting replicated to the server in question. Because the number of sudo rules did not change, and there was no change in the number of sudo rules, the check came back OK.

### Version of the project
2.7.4

### Version of the FreeIPA
4.4

### Version of the Operating System
CentOS 7.3.1611

**Comment by peterpakos** [comment]
@j-pavel not sure what you expect me to do here without actual steps to reproduce the problem.

I am yet to come across a system with an underlying problem affecting SUDO rules in the way you described it.

If you can provide me with some more details on the problem then I'll be happy to look in to it.
