### ISSUE TITLE
threshold setting for transient error

### ISSUE THREAD

**Issue by writertech** [peterpakos/checkipaconsistency#49]
### Expected behaviour
it should report FAIL, under certain conditions (after X number of minutes, 30/60/120/1800/etc)
### Actual behaviour
it's reporting OK
### Steps to reproduce the behaviour
you would have to run into a situation where you have a transient error for an extended period
### Version of the FreeIPA
4.5
### Version of the Operating System
RHEL7.4

### Notes
issue #74 was reported on an issue/case for a customer, however, after 30 hours of ipa reporting a 'transient' error, replication was still not happening (not a cipa issue). Instead of cipa 'always' reporting OK (and since we can use cipa as a Nagios plugin!!), the customer would like to be able to set a threshold for the number of minutes where a 'transient' error is no longer acceptable

**Comment by peterpakos** [comment]
@writertech, apologies for the delays in getting back to you (work and other projects took precedence).

Do you happen to have an example of said transient error?

Output of ldapsearch catching it would be ideal...

**Comment by peterpakos** [comment]
More information required, closing for now.

**Comment by writertech** [comment]
The info is in issue #47.. we/customers are using the version before #47 was added to at least still get the FAIL. It's just that FAIL is not helpful without digging further and determining how long it's been FAILing. The threshold addition would help immensely in dealing with these Nagios alerts.
