### ISSUE TITLE
command line switch for counts to include detail

### ISSUE THREAD

**Issue by writertech** [peterpakos/checkipaconsistency#50]
### Expected behaviour
count detail with the proper/new command line switch setting
### Actual behaviour
today, I believe the only counts are at the DN level?
### Version of the FreeIPA
4.5
### Version of the Operating System
RHEL7.4

### Notes
for example, the line for DNS Zones only counts the number of Zones across replicas, if not all replicas have the same number of A records (as one example), we would like to see there is an issue (which actually happened for a customer, and cipa was reporting all OK)
Just to clarify, this would not just be for DNS Zones, but for all items where cipa shows counts/STATE

**Comment by germanparente** [comment]
@writertech 

You can use the ds-replcheck utility delivered with FreeIPA to compare database contents very precisely.
Anyway, this tool will very likely show you there's a replication error somewhere and from there on, you can use ds-replcheck to have the details.

**Comment by peterpakos** [comment]
Thanks @germanparente.

@writertech if you feel this is not enough and the tool should handle it in a different manner, then feel free to reopen the issue.

Cheers.

**Comment by writertech** [comment]
customer was asking for this feature.. I don't see it implemented?
if not, can we keep this open until it get added?

**Comment by writertech** [comment]
(this would also fix #48 for us as well as all the other attributes (besides just sudo the bits being off))

**Comment by germanparente** [comment]
well, the tool is delivered with 389-ds-base rpm. The binary showing the difference details for each entry is /usr/bin/ds-replcheck
