### ISSUE TITLE
replication conflicts are not detected in recent version of FreeIPA

### ISSUE THREAD

**Issue by tscherf** [peterpakos/checkipaconsistency#56]
Replication conflict entries are now hidden and not visible with regular searches. This is because the objectclass 'ldapsubentry' is added to those objects. See the following ticket for details:

https://pagure.io/389-ds-base/issue/49043

And here is the design page:
http://www.port389.org/docs/389ds/design/managing-repl-conflict-entries.html

**Comment by peterpakos** [comment]
Fixed in fa0932e.
