### ISSUE TITLE
set the logger at FreeIPAServer object level

### ISSUE THREAD

**Issue by germanparente** [peterpakos/checkipaconsistency#60]
### Expected behaviour

when we set "--debug" all the debug messages at FreeIPAServer object cannot be seen because the logger is not sent to the object.

### Actual behaviour
We don't see the debug messages.

### Steps to reproduce the behaviour
use --debug

### Version of the FreeIPA
n/a

### Version of the Operating System
n/a

**Comment by peterpakos** [comment]
This has been fixed by 46fb109.
