### ISSUE TITLE
Optimization certificates verification

### ISSUE THREAD

**Issue by lucasdiedrich** [peterpakos/checkipaconsistency#67]
### Expected behaviour
When running cipa script it should verify the certificates faster or at least equals as users verification.

[root@ipa2 ~]# time cipa
+--------------------+---------------+---------------+---------+-------------+-------+
| FreeIPA servers:   | ipa           | ipa2          | ipa3   | ipa4 | STATE |
+--------------------+---------------+---------------+---------+-------------+-------+
| Active Users       | 10960         | 10960         | 10960   | 10960       | OK    |
| Stage Users        | 0             | 0             | 0       | 0           | OK    |
| Preserved Users    | 0             | 0             | 0       | 0           | OK    |
| Hosts              | 2099          | 2099          | 2099    | 2099        | OK    |
| Services           | 36            | 36            | 36      | 36          | OK    |
| User Groups        | 381           | 381           | 381     | 381         | OK    |
| Host Groups        | 11            | 11            | 11      | 11          | OK    |
| Netgroups          | 11            | 11            | 11      | 11          | OK    |
| HBAC Rules         | 9             | 9             | 9       | 9           | OK    |
| SUDO Rules         | 6             | 6             | 6       | 6           | OK    |
| DNS Zones          | 7             | 7             | 7       | 7           | OK    |
| Certificates       | 3097          | 3097          | 3097    | 0           | FAIL  |
| LDAP Conflicts     | 0             | 0             | 0       | 0           | OK    |
| Ghost Replicas     | 0             | 0             | 0       | 0           | OK    |
| Anonymous BIND     | ON            | ON            | ON      | ON          | OK    |
| Microsoft ADTrust  | True          | True          | True    | True        | OK    |
| Replication Status | ipa3 0       | ipa4 1 | ipa 1   | ipa 0       | FAIL  |
|                    | ipa4 0 | ipa 0         | ipa2 -5 | ipa2 0      |       |
|                    | ipa2 1        | ipa3 1       |         |             |       |
+--------------------+---------------+---------------+---------+-------------+-------+

***real	0m2,201s***  <<<<<<<<<<<---- FASTER
user	0m0,521s
sys	0m0,160s

### Actual behaviour
It takes one second peer CA replica to count objects.
[root@ipa2 ~]# time cipa
+--------------------+---------------+---------------+---------+-------------+-------+
| FreeIPA servers:   | ipa           | ipa2          | ipa3   | ipa4 | STATE |
+--------------------+---------------+---------------+---------+-------------+-------+
| Active Users       | 10960         | 10960         | 10960   | 10960       | OK    |
| Stage Users        | 0             | 0             | 0       | 0           | OK    |
| Preserved Users    | 0             | 0             | 0       | 0           | OK    |
| Hosts              | 2099          | 2099          | 2099    | 2099        | OK    |
| Services           | 36            | 36            | 36      | 36          | OK    |
| User Groups        | 381           | 381           | 381     | 381         | OK    |
| Host Groups        | 11            | 11            | 11      | 11          | OK    |
| Netgroups          | 11            | 11            | 11      | 11          | OK    |
| HBAC Rules         | 9             | 9             | 9       | 9           | OK    |
| SUDO Rules         | 6             | 6             | 6       | 6           | OK    |
| DNS Zones          | 7             | 7             | 7       | 7           | OK    |
| Certificates       | 3097          | 3097          | 3097    | 0           | FAIL  |
| LDAP Conflicts     | 0             | 0             | 0       | 0           | OK    |
| Ghost Replicas     | 0             | 0             | 0       | 0           | OK    |
| Anonymous BIND     | ON            | ON            | ON      | ON          | OK    |
| Microsoft ADTrust  | True          | True          | True    | True        | OK    |
| Replication Status | ipa3 0       | ipa4 0 | ipa 0   | ipa 0       | FAIL  |
|                    | ipa4 0 | ipa 0         | ipa2 -5 | ipa2 0      |       |
|                    | ipa2 0        | ipa3 0       |         |             |       |
+--------------------+---------------+---------------+---------+-------------+-------+

***real	0m3,688s*** <<<<<<<<<<<---- SLOW
user	0m1,284s
sys	0m0,268s
### Steps to reproduce the behaviour
time cipa

### Version of the project
cipa 2.7.7
### Version of the FreeIPA
freeipa-server-4.7.2-1.1.fc28.x86_64

### Version of the Operating System
Fedora release 28 (Twenty Eight)

**Comment by lucasdiedrich** [comment]
Hi, í'm having this time trouble most because of zabbix verification, i read the source code, and at [line 321](https://github.com/peterpakos/checkipaconsistency/blob/dbe0b456608740782051c66c37617266684fd683/checkipaconsistency/freeipaserver.py#L320) i made a small change, which became the verification faster (as seen over expected behavior). I just added a filter to bring one CN from the ldap search, if you wan't and aprove i can make a PR with it.

![image](https://user-images.githubusercontent.com/817482/55643771-58f4b600-57aa-11e9-8f3a-2b8eccebc260.png)

**Comment by lucasdiedrich** [comment]
@peterpakos , can i make the PR?

**Comment by peterpakos** [comment]
@lucasdiedrich go for it!

**Comment by lucasdiedrich** [comment]
@peterpakos, done at PR #69 

Thanks.

**Comment by peterpakos** [comment]
Fixed in 2.7.11 (7689e67).

Thanks @lucasdiedrich!
