### ISSUE TITLE
bash: Pmkrb: command not found

### ISSUE THREAD

**Issue by tobmat** [peterpakos/checkipaconsistency#68]
### Expected behaviour
Return output from ldap server

### Actual behaviour
bash: Pmkrb: command not found
[~/.config]
toby.matherly CORP-L-66FJG5J -> Initial config saved to /Users/toby.matherly/.config/checkipaconsistency - PLEASE EDIT IT!
+--------------------+-------+-------+-------+------------+-------+-------+-------+-------+
| FreeIPA servers:   | idm04 | idm05 | idm07 | idm-master | idm06 | idm03 | idm02 | STATE |
+--------------------+-------+-------+-------+------------+-------+-------+-------+-------+
| Active Users       | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Stage Users        | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Preserved Users    | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Hosts              | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Services           | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| User Groups        | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Host Groups        | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Netgroups          | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| HBAC Rules         | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| SUDO Rules         | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| DNS Zones          | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Certificates       | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| LDAP Conflicts     | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Ghost Replicas     | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Anonymous BIND     | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Microsoft ADTrust  | None  | None  | None  | None       | None  | None  | None  | FAIL  |
| Replication Status | None  | None  | None  | None       | None  | None  | None  | FAIL  |
+--------------------+-------+-------+-------+------------+-------+-------+-------+-------+

### Steps to reproduce the behaviour
pip3 install checkipaconsistency
cipa -d karit.internal -W "domain pw"

### Version of the project
current pip3 version

### Version of the FreeIPA
FreeIPA, version: 4.6.4

### Version of the Operating System
macOS Mojave version 10.14.4

Note: Another person using a Mac against same IPA has had successful results.

**Comment by tobmat** [comment]
You can disregard this issue.  It turns out I just needed to put my domain pw in quotes.

**Comment by gearboxscott** [comment]
Put single quotes around the cn=Directory Manager password will eliminate the error.
